### ISSUE TITLE
Multifasta file.

### ISSUE THREAD

**Issue by jaehoonLee** [mcollatz/EpiDope#5]
Hi mcollatz

Thanks for interesting project, and I am deep dived into understading epitope.
I am trying to run code, but I am not sure how can I get multifasta file? 

Can you help me?

**Comment by flomock** [comment]
Hi @jaehoonLee,
I'm not sure if I understand your question correctly. 
If your question is where you can get multifasta files, you can find many databases with protein fasta files, for example: https://www.ncbi.nlm.nih.gov/protein/P0DTC2 (a SARS2 protein on ncbi). Multifastas are simply concatenated fasta files, see: http://www.metagenomics.wiki/tools/fastq/multi-fasta-format
If your question is how you run a multifasta file in EpiDope, then the answer is simple:
`epidope -i yourmultifasta.fa`
the inputfile (yourmultifasta.fa) can be a single or a multifasta. Both should work.

If however, you experience errors or problems running your multifasta with EpiDope, please describe your issue in more detail.

**Comment by flomock** [comment]
We now have a new version. :)
Maybe you can try to delete the old conda enviroment and install the new version.

Greetings,
Florian

**Comment by jaehoonLee** [comment]
My question was where I can get multifast files. Thanks for explanation and clarification.
It is helpful to me.

**Comment by mcollatz** [comment]
You can get fasta files by downloading the protein sequence from of any protein data base. For example the ncbi (https://www.ncbi.nlm.nih.gov/protein/AAC68276.1?report=fasta). Another example of a multi fasta file is an entire proteome which is the concatenation of its single protein fastas. This could be downloaded from uniprot (https://www.uniprot.org/proteomes/UP000000431).
