### ISSUE TITLE
EpiDope docker fails

### ISSUE THREAD

**Issue by abrozzi** [mcollatz/EpiDope#7]
docker run -t --rm -v /Users/abrozzi/P08191.fasta:/in -v /Users/abrozzi/OUTPUT:/out flomock/epidope:v0.2 -i /in/proteins.fasta -o /out/epidope_results
Traceback (most recent call last):
  File "/opt/conda/bin/epidope", line 33, in <module>
    sys.exit(load_entry_point('EpiDope==0.2', 'console_scripts', 'epidope')())
  File "/opt/conda/lib/python3.7/site-packages/epidope/cli.py", line 47, in cli
    assert os.path.isfile(args.infile), f"error {args.infile} is not a file"
AssertionError: error /in/proteins.fasta is not a file

**Comment by matdoering** [comment]
Works for me. You forgot to udpate the input path:

docker run -t --rm -v /Users/abrozzi/P08191.fasta:/in -v /Users/abrozzi/OUTPUT:/out flomock/epidope:v0.2 -i /in/**P08191.fasta** -o /out/epidope_results
